apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: "http"
      port: {{ .Values.envVariables.backend.port }}
      targetPort: {{ .Values.envVariables.backend.port }}
