apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ int .Values.config.replicas.medium }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
    spec:
      containers:
        - image: {{ .Values.images.backend.repo }}:{{ .Values.images.tag }}
          name: frontend
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: {{ .Values.envVariables.backend.port }}

