version: '3.1'

services:
  backend:
    build: ./api
    container_name: backend
    ports:
    - 5000:5000

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
    - backend
    environment:
    - NODE_ENV=production
    ports:
    - 80:3000