apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lexiko-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: lexiko-ingress
spec:
  defaultBackend:
    service:
      name: pheidias-service
      port:
        number: {{ .Values.envVariables.pheidias.port }}
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pheidias-service
                port:
                  number: {{ .Values.envVariables.pheidias.port }}
          - pathType: Prefix
            path: /api/v1
            backend:
              service:
                name: sokrates-service
                port:
                  number: {{ .Values.envVariables.sokrates.port }}
