apiVersion: v1
kind: Service
metadata:
  name: alexandros-service
spec:
  selector:
    app: alexandros
  ports:
    - name: "http"
      port: {{ .Values.envVariables.alexandros.port }}
      targetPort: {{ .Values.envVariables.alexandros.port }}
