apiVersion: v1
kind: Service
metadata:
  name: herodotos-service
spec:
  selector:
    app: herodotos
  ports:
    - name: "http"
      port: {{ .Values.envVariables.herodotos.port }}
      targetPort: {{ .Values.envVariables.herodotos.port }}
