apiVersion: apps/v1
kind: Deployment
metadata:
  name: herodotos
  labels:
    app: herodotos
spec:
  replicas: {{ int .Values.config.replicas.low }}
  selector:
    matchLabels:
      app: herodotos
  template:
    metadata:
      labels:
        app: herodotos
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
    spec:
      containers:
        - image: {{ .Values.images.herodotos.repo }}:{{ .Values.images.tag }}
          name: sokrates
          env:
            - name: ELASTIC_SEARCH_SERVICE
              value: {{ .Values.envVariables.elastic.elasticService }}
            - name: ELASTIC_SEARCH_USER
              value: {{ .Values.envVariables.elastic.elasticUser }}
            - name: ELASTIC_SEARCH_PASSWORD
              value: {{ .Values.envVariables.elastic.elasticPassword }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: {{ .Values.envVariables.herodotos.port }}
