apiVersion: v1
kind: Service
metadata:
  name: sokrates-service
spec:
  selector:
    app: sokrates
  ports:
    - name: "http"
      port: {{ .Values.envVariables.sokrates.port }}
      targetPort: {{ .Values.envVariables.sokrates.port }}
