# Default values for Lexiko.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: development
  pullPolicy: Never
  replicas:
    low: 1
    medium: 3
    high: 5

images:
  tag: d07992c
  pheidias:
    repo: pheidias
  sokrates:
    repo: sokrates
  parmenides:
    repo: parmenides

envVariables:
  pheidias:
    nodeEnv: production
    port: 3000
  sokrates:
    port: 5000
  elastic:
    elasticService: http://elasticsearch-master:9200
    elasticUser: elastic
    elasticPassword: lexiko