# Default values for Lexiko.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: development
  pullPolicy: Never
  replicas:
    low: 1
    medium: 3
    high: 5

images:
  tag: bc44aa9
  alexandros:
    repo: alexandros
  pheidias:
    repo: pheidias
  sokrates:
    repo: sokrates
  parmenides:
    repo: parmenides
  demokritos:
    repo: demokritos
  herodotos:
    repo: herodotos
  herakleitos:
    repo: herakleitos
  ploutarchos:
    repo: ploutarchos

envVariables:
  pheidias:
    nodeEnv: production
    port: 3000
  alexandros:
    port: 5000
  sokrates:
    port: 5000
  herodotos:
    port: 5000
  ploutarchos:
    port: 8080
  elastic:
    elasticService: http://elasticsearch-master:9200
    elasticUser: elastic
    elasticPassword: lexiko