apiVersion: batch/v1
kind: Job
metadata:
  name: demokritos
  labels:
    app: demokritos
spec:
  template:
    metadata:
      labels:
        app: demokritos
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
    spec:
      containers:
        - image: {{ .Values.images.demokritos.repo }}:{{ .Values.images.tag }}
          name: demokritos
          env:
            - name: ELASTIC_SEARCH_SERVICE
              value: {{ .Values.envVariables.elastic.elasticService }}
            - name: ELASTIC_SEARCH_USER
              value: {{ .Values.envVariables.elastic.elasticUser }}
            - name: ELASTIC_SEARCH_PASSWORD
              value: {{ .Values.envVariables.elastic.elasticPassword }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
      restartPolicy: Never
  backoffLimit: 3
