# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: development
  pullPolicy: Never
  inClusterElastic: true
  replicas:
    low: 1
    medium: 2
    high: 4
  initialDelayLiveness: 20
  initialDelayReadiness: 1
  periodSeconds: 20


services:
  hippokrates:
    testing: true
    name: "hippokrates"
    # additionals labels
    labels: {
              domain: testing
    }
  alexandros:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  herodotos:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  sokrates:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"

images:
  tag: 8fd310b
  alexandros:
    repo: alexandros
  pheidias:
    repo: pheidias
  sokrates:
    repo: sokrates
  parmenides:
    repo: parmenides
  demokritos:
    repo: demokritos
  herodotos:
    repo: herodotos
  herakleitos:
    repo: herakleitos
  ploutarchos:
    repo: ploutarchos
  hippokrates:
    repo: hippokrates

envVariables:
  pheidias:
    nodeEnv: production
    port: 3000
  alexandros:
    port: 5000
  sokrates:
    port: 5000
  herodotos:
    port: 5000
  ploutarchos:
    port: 8080
  elastic:
    elasticService: http://elasticsearch-master:9200
    elasticUser: elastic
    elasticPassword: odysseia