apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexandros
  labels:
    app: alexandros
spec:
  replicas: {{ int .Values.config.replicas.high }}
  selector:
    matchLabels:
      app: alexandros
  template:
    metadata:
      labels:
        app: alexandros
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
    spec:
      containers:
        - image: {{ .Values.images.alexandros.repo }}:{{ .Values.images.tag }}
          name: alexandros
          env:
            - name: ELASTIC_SEARCH_SERVICE
              value: {{ .Values.envVariables.elastic.elasticService }}
            - name: ELASTIC_SEARCH_USER
              value: {{ .Values.envVariables.elastic.elasticUser }}
            - name: ELASTIC_SEARCH_PASSWORD
              value: {{ .Values.envVariables.elastic.elasticPassword }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: {{ .Values.envVariables.alexandros.port }}
