apiVersion: apps/v1
kind: Deployment
metadata:
  name: pheidias
  labels:
    app: pheidias
spec:
  replicas: {{ int .Values.config.replicas.low }}
  selector:
    matchLabels:
      app: pheidias
  template:
    metadata:
      labels:
        app: pheidias
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - image: {{ .Values.images.pheidias.repo }}:{{ .Values.images.tag }}
          name: frontend
          env:
            - name: NODE_ENV
              value: {{ .Values.envVariables.pheidias.nodeEnv }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: {{ .Values.envVariables.pheidias.port }}
