apiVersion: v1
kind: Service
metadata:
  name: pheidias-service
spec:
  selector:
    app: pheidias
  ports:
    - name: "http"
      port: {{ .Values.envVariables.pheidias.port }}
      targetPort: {{ .Values.envVariables.pheidias.port }}
