apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ int .Values.config.replicas.low }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
    spec:
      containers:
        - image: {{ .Values.images.frontend.repo }}:{{ .Values.images.tag }}
          name: frontend
          env:
            - name: NODE_ENV
              value: {{ .Values.envVariables.frontend.nodeEnv }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: {{ .Values.envVariables.frontend.port }}
