apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: "http"
      port: {{ .Values.envVariables.frontend.port }}
      targetPort: {{ .Values.envVariables.frontend.port }}
